"""add organizational module

Revision ID: d4001e3e0a05
Revises: 0ee586132d1b
Create Date: 2026-04-23 16:19:44.563401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4001e3e0a05'
down_revision = '0ee586132d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_periods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','closed','cancelled')", name='ck_management_periods_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_management_periods_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('instance_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("instance_type in ('teacher_representation','academic_authority','union_organization','committee','other')", name='ck_organizational_instances_type'),
    sa.CheckConstraint("level in ('university','faculty','career','federation','association','other')", name='ck_organizational_instances_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('position_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supporting_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type in ('resolution','minutes','note','memorandum','call','certificate','other')", name='ck_supporting_documents_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incompatibility_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_group_id', sa.BigInteger(), nullable=False),
    sa.Column('target_group_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('origin_group_id <> target_group_id', name='ck_incompatibility_rules_different_groups'),
    sa.ForeignKeyConstraint(['origin_group_id'], ['position_groups.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['position_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_group_id', 'target_group_id', name='uq_incompatibility_rules_groups')
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('position_group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['organizational_instances.id'], ),
    sa.ForeignKeyConstraint(['position_group_id'], ['position_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'name', name='uq_positions_instance_name')
    )
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_signer', sa.Boolean(), nullable=False),
    sa.Column('supporting_document_id', sa.BigInteger(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','finished','revoked','cancelled')", name='ck_appointments_status'),
    sa.CheckConstraint('end_date is null or end_date >= start_date', name='ck_appointments_dates'),
    sa.ForeignKeyConstraint(['period_id'], ['management_periods.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['supporting_document_id'], ['supporting_documents.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('positions')
    op.drop_table('incompatibility_rules')
    op.drop_table('supporting_documents')
    op.drop_table('position_groups')
    op.drop_table('organizational_instances')
    op.drop_table('management_periods')
    # ### end Alembic commands ###
