# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Proyecto monorepo:
# - backend/  -> Flask
# - frontend/ -> Angular

name: Build and deploy Flask backend to Azure Web App - fedsidumsa-system-umsa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create backend deployment zip
        run: |
          cd backend
          zip -r ../backend-app.zip . -x "antenv/*" "__pycache__/*" "*.pyc" ".git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: backend-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DDC49C386BBB4DEFA38245D47952FEA9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF54C44CF13D4662B58141B636AFEB33 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0B23E80AC624B53BDCDAF9CA0AB7A59 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'fedsidumsa-system-umsa'
          slot-name: 'Production'
          package: backend-app.zip
